apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-simple
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/himeshpanc/guestbook
      imageSelectionStrategy: SemVer
  # Add this to track your Git repo
  - git:
      repoURL: https://github.com/himeshpanc/kargo-simple-demo.git
      branch: main
      paths:
      - base/  # Only watch the base directory for changes